name: Recreate collections and indexes

on:
  workflow_dispatch:

jobs:
  installContentful:
    name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup contentful
        id: setupContentful
        uses: autotelic/setup-contentful@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          version: v1.16.7
      - run: sudo chmod a+x ${{ steps.setupContentful.outputs.contentfulPath }}/contentful
      - name: Bulk indexing
        id: bulkIndexing
        uses: autotelic/contentful-typesense@main
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://3dkfm1xc8uen7v4rp-1.a1.typesense.net
          typesenseAction: bulkIndexing
