name: Recreate collections and indexes

on:
  workflow_dispatch:

jobs:
  dropAndCreateCollections:
    runs-on: ubuntu-latest
    name: Drop and re-create Typesense collections
    steps:
      - uses: autotelic/contentful-typesense@v0.4.0
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://3dkfm1xc8uen7v4rp-1.a1.typesense.net
          typesenseAction: dropAndCreateCollections

  # reIndex:
  #   runs-on: ubuntu-latest
  #   name: Re-index contentful data into Typesense
  #   steps:
  #     - uses: autotelic/contentful-typesense@v0.3.0
  #       with:
  #         contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
  #         typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
  #         contentfulSpaceId: opxulaoc9o1m
  #         typesenseUrl: https://3dkfm1xc8uen7v4rp-1.a1.typesense.net
  #         typesenseAction: bulkIndexing
