name: Drop and create collections on prod

on:
  workflow_dispatch:

jobs:
  dropAndCreateCollections:
    name: Drop and create collections on prod
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Drop and create collections
        id: dropAndCreateCollections
        uses: autotelic/contentful-typesense@main
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://6dk804acb3pntfy1p-1.a1.typesense.net
          typesenseAction: dropAndCreateCollections
          includeDrafts: false
