name: Bulk indexing prod

on:
  workflow_dispatch:

jobs:
  bulkIndexing:
    name: Bulk update of prod index from contentful
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Setup contentful
        id: setupContentful
        uses: autotelic/setup-contentful@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          version: v1.16.7
      - run: sudo chmod a+x ${{ steps.setupContentful.outputs.contentfulPath }}/contentful
      - name: Bulk indexing
        id: bulkIndexing
        uses: autotelic/contentful-typesense@main
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://6dk804acb3pntfy1p-1.a1.typesense.net
          typesenseAction: bulkIndexing
          includeDrafts: false
