name: Update index from webhook on prod

on:
  repository_dispatch:
    types: [contentful_webhook_prod]

jobs:
  updateIndex:
    name: Update prod index from contentful
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Update index
        id: updateIndex
        uses: autotelic/contentful-typesense@main
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://6dk804acb3pntfy1p-1.a1.typesense.net
          includeDrafts: false
