name: Drop and create collections on staging

on:
  workflow_dispatch:

jobs:
  dropAndCreateCollections:
    name: Drop and create collections on staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - uses: actions/checkout@v3
      - name: Drop and create collections
        id: dropAndCreateCollections
        uses: autotelic/contentful-typesense@main
        with:
          contentManagementToken: ${{ secrets.CONTENFUL_CMA_KEY }}
          typesenseAdminApiKey: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          contentfulSpaceId: opxulaoc9o1m
          typesenseUrl: https://3dkfm1xc8uen7v4rp-1.a1.typesense.net
          typesenseAction: dropAndCreateCollections
          includeDrafts: true
          contentTypeMappingsPath: contentTypeMappings.js
